// Copies the web client served by the Python host into the Capacitor web root.
// The layout is kept identical (index.html at the root, everything else under
// /assets) so the very same files work in the browser and inside the APK.
//
// SEOS_SERVER_URL=https://plan.example.com npm run sync
//   presets the API server (default: the hosted server; still changeable under
//   Settings → Advanced). SEOS_SERVER_URL= (empty) asks for it on first launch.
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, '../src/student_execution_os/web/static');
const www = resolve(root, 'www');

rmSync(www, { recursive: true, force: true });
mkdirSync(resolve(www, 'assets'), { recursive: true });
cpSync(source, resolve(www, 'assets'), { recursive: true, filter: (p) => !p.endsWith('index.html') });
// On WebViews without document-start script support Capacitor injects its native bridge
// as an inline <script>; the bundled page therefore allows inline scripts. The browser
// build keeps the strict policy (the Python host also sends it as a header).
const html = readFileSync(resolve(source, 'index.html'), 'utf8');
const nativeHtml = html.replace("script-src 'self'", "script-src 'self' 'unsafe-inline'");
if (nativeHtml === html) {
  console.error('index.html CSP meta tag not found; update sync-web.mjs');
  process.exit(1);
}
writeFileSync(resolve(www, 'index.html'), nativeHtml);

// The consumer build talks to the project's hosted server, so a new user starts with
// the product instead of a server address. SEOS_SERVER_URL overrides it; setting it to
// an empty string builds a self-hosting app that asks for the address on first launch.
const HOSTED_SERVER = 'https://seos.185-102-139-43.sslip.io';
const server = (process.env.SEOS_SERVER_URL ?? HOSTED_SERVER).trim().replace(/\/+$/, '');
if (server && !/^https?:\/\//.test(server)) {
  console.error(`SEOS_SERVER_URL must start with http:// or https:// (got "${server}")`);
  process.exit(1);
}
// Firebase is only initialised when the build includes google-services.json; calling
// PushNotifications.register() without it crashes the native bridge, so the web
// client registers for push only when this build flag is set.
const pushEnabled = existsSync(resolve(root, 'android/app/google-services.json'));
writeFileSync(
  resolve(www, 'assets/config.js'),
  `// Generated by mobile/scripts/sync-web.mjs\nwindow.SEOS_CONFIG = ${JSON.stringify({ defaultServerUrl: server, pushEnabled })};\n`,
);
console.log(`web client copied to ${www}${server ? ` (default server ${server})` : ''}; push ${pushEnabled ? 'enabled' : 'disabled (no google-services.json)'}`);
